version: '3'
services:
  mongodb:
    image: mongo
    container_name: shortsSniperContainer
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./init-scripts:/docker-entrypoint-initdb.d
    env_file:
      - .env  
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
